definitions:
  dto.BasicResponse:
    properties:
      code:
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      err:
        type: string
    type: object
  dto.ExerciseDateInfo:
    properties:
      date:
        example: YYYY-MM-DD
        type: string
      exercises:
        items:
          $ref: '#/definitions/dto.ExerciseDoneInfo'
        type: array
    type: object
  dto.ExerciseDo:
    properties:
      exercise_id:
        type: integer
      performed_date:
        example: YYYY-MM-DD
        type: string
    type: object
  dto.ExerciseDoneInfo:
    properties:
      done:
        type: boolean
      exercise:
        $ref: '#/definitions/dto.ExerciseResponse'
    type: object
  dto.ExerciseRequest:
    properties:
      exercise_end_at:
        example: HH:mm
        type: string
      exercise_start_at:
        example: HH:mm
        type: string
      id:
        type: integer
      plan_end_at:
        example: YYYY-MM-DD
        type: string
      plan_start_at:
        example: YYYY-MM-DD
        type: string
      title:
        type: string
      use_alarm:
        type: boolean
      weekdays:
        items:
          type: integer
        type: array
    type: object
  dto.ExerciseResponse:
    properties:
      created:
        type: string
      exercise_end_at:
        example: HH:mm
        type: string
      exercise_start_at:
        example: HH:mm
        type: string
      id:
        type: integer
      plan_end_at:
        example: YYYY-MM-DD
        type: string
      plan_start_at:
        example: YYYY-MM-DD
        type: string
      updated:
        type: string
      use_alarm:
        type: boolean
      weekdays:
        items:
          type: integer
        type: array
    type: object
info:
  contact: {}
paths:
  /do-exercises:
    post:
      consumes:
      - application/json
      description: 운동 완료/취소시 호출
      parameters:
      - description: 운동 완료/취소 데이터
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ExerciseDo'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 운동 기록
      tags:
      - 운동
  /get-exercises:
    get:
      description: 운동 조회시 호출
      parameters:
      - description: 시작날짜 yyyy-mm-dd
        in: query
        name: start_date
        type: string
      - description: 종료날짜 yyyy-mm-dd
        in: query
        name: end_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 운동정보
          schema:
            items:
              $ref: '#/definitions/dto.ExerciseDateInfo'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 운동 조회
      tags:
      - 운동
  /remove-exercise:
    post:
      consumes:
      - application/json
      description: 운동 삭제시 호출
      parameters:
      - description: 삭제할 id 배열
        in: body
        name: request
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 운동 삭제
      tags:
      - 운동
  /save-exercise:
    post:
      description: 운동 생성시 Id 생략
      parameters:
      - description: 요청 DTO - 운동 데이터
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ExerciseRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 운동 생성/수정
      tags:
      - 운동
swagger: "2.0"
