definitions:
  dto.BasicResponse:
    properties:
      code:
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      err:
        type: string
    type: object
  dto.SleepAlarmRequest:
    properties:
      alarm_time:
        type: string
      end_time:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      start_time:
        type: string
      weekdays:
        items:
          type: integer
        type: array
    type: object
  dto.SleepAlarmResponse:
    properties:
      created:
        type: string
      end_time:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      start_time:
        type: string
      updated:
        type: string
      weekdays:
        items:
          type: integer
        type: array
    type: object
  dto.SleepTimeRequest:
    properties:
      date_sleep:
        type: string
      end_time:
        type: string
      start_time:
        type: string
    type: object
  dto.SleepTimeResponse:
    properties:
      date_sleep:
        type: string
      end_time:
        type: string
      id:
        type: integer
      start_time:
        type: string
    type: object
info:
  contact: {}
paths:
  /get-sleep-alarms:
    get:
      description: 수만알람 조회시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 수면 알람정보
          schema:
            items:
              $ref: '#/definitions/dto.SleepAlarmResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 수면알람 조회
      tags:
      - 수면
  /get-sleep-times:
    get:
      description: 기간별 수면시간 조회시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 시작날짜 yyyy-mm-dd
        in: query
        name: start_date
        required: true
        type: string
      - description: 종료날짜 yyyy-mm-dd
        in: query
        name: end_date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 수면시간 정보
          schema:
            items:
              $ref: '#/definitions/dto.SleepTimeResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 기간별 수면시간 조회
      tags:
      - 수면
  /remove-sleep-alarms:
    post:
      consumes:
      - application/json
      description: 수면 알림 삭제시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 삭제할 id 배열
        in: body
        name: request
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 수면알림 삭제
      tags:
      - 수면
  /remove-sleep-times/{id}:
    post:
      consumes:
      - application/json
      description: 수면 시간 삭제시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 수면시간 ID
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 수면시간 삭제
      tags:
      - 수면
  /save-sleep:
    post:
      description: 수면알림 생성시 Id 생략
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 수면알림 DTO - 수면알림 데이터
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.SleepAlarmRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 수면알림 생성/수정
      tags:
      - 수면
  /save-sleep-time:
    post:
      consumes:
      - application/json
      description: 수면시간 등록/수정 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 수면시간 DTO - 수면시간 데이터
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.SleepTimeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 수면시간 등록/수정
      tags:
      - 수면
swagger: "2.0"
