definitions:
  dto.BasicResponse:
    properties:
      code:
        type: string
    type: object
  dto.DietPresetRequest:
    properties:
      foods:
        items:
          type: string
        type: array
      id:
        type: integer
      name:
        type: string
    type: object
  dto.DietPresetResponse:
    properties:
      created:
        example: 'YYYY-mm-ddTHH:mm:ss '
        type: string
      foods:
        items:
          type: string
        type: array
      id:
        type: integer
      name:
        type: string
      updated:
        example: 'YYYY-mm-ddTHH:mm:ss '
        type: string
    type: object
  dto.DietRequest:
    properties:
      foods:
        items:
          type: string
        type: array
      id:
        type: integer
      images:
        example:
        - base64 encoding string
        items:
          type: string
        type: array
      name:
        type: string
      time:
        example: HH:mm
        type: string
      type:
        type: integer
    type: object
  dto.DietResponse:
    properties:
      created:
        example: 'YYYY-mm-ddTHH:mm:ss '
        type: string
      foods:
        items:
          type: string
        type: array
      id:
        type: integer
      images:
        items:
          $ref: '#/definitions/dto.ImageResponse'
        type: array
      name:
        type: string
      time:
        type: string
      type:
        type: integer
      updated:
        example: 'YYYY-mm-ddTHH:mm:ss '
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      err:
        type: string
    type: object
  dto.ImageResponse:
    properties:
      thumbnail_url:
        type: string
      url:
        type: string
    type: object
info:
  contact: {}
paths:
  /get-diets:
    get:
      description: 식단 조회시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 시작날짜 yyyy-mm-dd
        in: query
        name: start_date
        type: string
      - description: 종료날짜 yyyy-mm-dd
        in: query
        name: end_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 식단정보 type - 아침/점심/저녁/간식 1/2/3/4
          schema:
            items:
              $ref: '#/definitions/dto.DietResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 식단 조회
      tags:
      - 식단 /diet
  /get-presets:
    get:
      description: 추가한 식단 조회시 호출 (10개씩)
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 페이지 번호 default 0
        in: query
        name: page
        type: integer
      - description: 시작날짜 yyyy-mm-dd
        in: query
        name: start_date
        type: string
      - description: 종료날짜 yyyy-mm-dd
        in: query
        name: end_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 식단정보
          schema:
            items:
              $ref: '#/definitions/dto.DietPresetResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 추가한 식단 조회
      tags:
      - 식단 /diet
  /remove-diet:
    post:
      consumes:
      - application/json
      description: 추가한 식단 삭제시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 삭제할 id 배열
        in: body
        name: request
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 추가한 식단 삭제
      tags:
      - 식단 /diet
  /remove-preset:
    post:
      consumes:
      - application/json
      description: 추가한 식단 삭제시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 삭제할 id 배열
        in: body
        name: request
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 추가한 식단 삭제
      tags:
      - 식단 /diet
  /save-diet:
    post:
      description: 식단생성시 Id 생략
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 요청 DTO - 식단데이터 type - 아침/점심/저녁/간식 1/2/3/4
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.DietRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 식단생성/수정
      tags:
      - 식단 /diet
  /save-preset:
    post:
      description: 추가한 식단 생성시 Id 생략
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 요청 DTO - 추가한 식단 데이터
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.DietPresetRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 추가한 식단 생성/수정
      tags:
      - 식단 /diet
swagger: "2.0"
