version: '3.8'
services:
  gateway:
    image: disterbia94/wellkinson_gateway
    ports:
      - "50000:50000"
    depends_on:
      - admin
      - alarm
      - diet
      - email
      - emotion
      - exercise
      - face
      - fcm
      - inquire
      - medicine
      - sleep
      - user
      - vocal
# ...
  admin:
    image: disterbia94/wellkinson_admin_video_service

  alarm:
    image: disterbia94/wellkinson_alarm_service

  diet:
    image: disterbia94/wellkinson_diet_service

  email:
    image: disterbia94/wellkinson_email_service

  emotion:
    image: disterbia94/wellkinson_emotion_service

  exercise:
    image: disterbia94/wellkinson_exercise_service
  
  face:
    image: disterbia94/wellkinson_face_service

  fcm:
    image: disterbia94/wellkinson_fcm_service

  inquire:
    image: disterbia94/wellkinson_inquire_service

  medicine:
    image: disterbia94/wellkinson_medicine_service

  sleep:
    image: disterbia94/wellkinson_sleep_service

  user:
    image: disterbia94/wellkinson_user_service

  vocal:
    image: disterbia94/wellkinson_vocal_service

networks:
  default:
    name: my_network