definitions:
  dto.BasicResponse:
    properties:
      code:
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      err:
        type: string
    type: object
  dto.VimeoLevel1:
    properties:
      name:
        type: string
      project_id:
        type: string
    type: object
  dto.VimeoLevel2:
    properties:
      is_active:
        type: boolean
      name:
        type: string
      video_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /get-items:
    get:
      description: 최초에 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 웰킨스 폴더 내용
          schema:
            items:
              $ref: '#/definitions/dto.VimeoLevel1'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 최상위 레벨 조회
      tags:
      - 관리자 동영상 관리 /admin-video
  /get-items/{id}:
    get:
      description: 폴더내부 조회시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 해당 폴더 내용
          schema:
            items:
              $ref: '#/definitions/dto.VimeoLevel2'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 폴더 레벨2 조회
      tags:
      - 관리자 동영상 관리 /admin-video
  /save-videos/{id}:
    post:
      description: 활성화 동영상 변경시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 활성화 할 id 배열
        in: body
        name: request
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 동영상 활성화
      tags:
      - 관리자 동영상 관리 /admin-video
swagger: "2.0"
