definitions:
  dto.BasicResponse:
    properties:
      code:
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      err:
        type: string
    type: object
  dto.VocalScoreRequest:
    properties:
      score:
        type: integer
      type:
        type: integer
    type: object
  dto.VocalScoreResponse:
    properties:
      created:
        example: 'YYYY-mm-ddTHH:mm:ssZ (ISO8601) '
        type: string
      score:
        type: integer
      type:
        type: integer
      updated:
        example: 'YYYY-mm-ddTHH:mm:ssZ (ISO8601) '
        type: string
    type: object
  dto.VoiceWordResponse:
    properties:
      title:
        type: string
      type:
        type: integer
    type: object
info:
  contact: {}
paths:
  /get-vocal-scores:
    get:
      description: 발성 점수 조회시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 시작날짜 yyyy-mm-dd
        in: query
        name: start_date
        type: string
      - description: 종료날짜 yyyy-mm-dd
        in: query
        name: end_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 표정검사 점수 정보
          schema:
            items:
              $ref: '#/definitions/dto.VocalScoreResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 발성 점수 조회
      tags:
      - 발성 /vocal
  /get-voice-tables:
    get:
      description: 발성운동 단어 조회시 호출
      produces:
      - application/json
      responses:
        "200":
          description: 발성운동 단어 데이터
          schema:
            items:
              $ref: '#/definitions/dto.VoiceWordResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 발성운동 단어 조회
      tags:
      - 발성 /vocal
  /save-vocals:
    post:
      description: 발성 검사 완료 후 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: '요청 DTO - 발성검사 데이터 ( type: 1:a 2:e 3:i 4:o 5:u )'
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/dto.VocalScoreRequest'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 발성 점수 저장
      tags:
      - 발성 /vocal
swagger: "2.0"
