definitions:
  dto.AlarmRequest:
    properties:
      body:
        example: 알람내용
        type: string
      end_at:
        example: yyyy-mm-dd
        type: string
      id:
        type: integer
      start_at:
        example: yyyy-mm-dd
        type: string
      timestamp:
        example: HH:mm
        type: string
      type:
        type: integer
      week:
        items:
          type: integer
        type: array
    type: object
  dto.AlarmResponse:
    properties:
      body:
        example: 알람내용
        type: string
      created:
        example: 'YYYY-mm-ddTHH:mm:ss '
        type: string
      end_at:
        example: yyyy-mm-dd
        type: string
      id:
        type: integer
      start_at:
        example: yyyy-mm-dd
        type: string
      timestamp:
        example: HH:mm
        type: string
      type:
        type: integer
      updated:
        example: 'YYYY-mm-ddTHH:mm:ss '
        type: string
      week:
        items:
          type: integer
        type: array
    type: object
  dto.BasicResponse:
    properties:
      code:
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      err:
        type: string
    type: object
info:
  contact: {}
paths:
  /get-notis:
    get:
      description: 수신 알림 조회시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 알람정보 - type 1:운동 2:약 3:수면
          schema:
            items:
              $ref: '#/definitions/dto.AlarmResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 수신 알림 조회
      tags:
      - 알람 /alarm
  /get-presets:
    get:
      description: 등록된 알람조회시 호출 (10개씩)
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 페이지 번호 default 0
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 알람정보 - type 1:운동 2:약 3:수면
          schema:
            items:
              $ref: '#/definitions/dto.AlarmResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 등록된 알람 조회
      tags:
      - 알람 /alarm
  /read-notis:
    post:
      consumes:
      - application/json
      description: 수신 알림 조회시 자동 읽음 처리라면 수신 알림 조회완료 후 함께 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 알림 모두 읽기
      tags:
      - 알람 /alarm
  /remove-alarms:
    post:
      consumes:
      - application/json
      description: 알람삭제시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 삭제할 id 배열
        in: body
        name: request
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 알람삭제
      tags:
      - 알람 /alarm
  /remove-notis:
    post:
      consumes:
      - application/json
      description: 수신된 알림 삭제시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 삭제할 id 배열
        in: body
        name: request
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 수신된 알림 삭제
      tags:
      - 알람 /alarm
  /save-alarm:
    post:
      consumes:
      - application/json
      description: 알람생성시 id생략 / 알람수정시 id 포함
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 요청 DTO - 알람데이터, type 1:운동 2:약 3:수면
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.AlarmRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 알람생성/수정
      tags:
      - 알람 /alarm
swagger: "2.0"
