// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/do-exercises": {
            "post": {
                "description": "운동 완료/취소시 호출",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "운동"
                ],
                "summary": "운동 기록",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {jwt_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "운동 완료/취소 데이터",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ExerciseDo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공시 200 반환",
                        "schema": {
                            "$ref": "#/definitions/dto.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/get-exercises": {
            "get": {
                "description": "운동 조회시 호출",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "운동"
                ],
                "summary": "운동 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {jwt_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "시작날짜 yyyy-mm-dd",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "종료날짜 yyyy-mm-dd",
                        "name": "end_date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "운동정보",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ExerciseDateInfo"
                            }
                        }
                    },
                    "400": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/get-projects": {
            "get": {
                "description": "운동 동영상 카테고리 조회시 호출",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "운동"
                ],
                "summary": "운동 동영상 카테고리 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {jwt_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "카테고리 정보",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ProjectResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/get-videos": {
            "get": {
                "description": "카테고리별 운동 동영상 조회시 호출",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "운동"
                ],
                "summary": "카테고리별 운동 동영상 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {jwt_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "project_id",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "페이지 default 0",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "동영상 정보",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.VideoResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/remove-exercise": {
            "post": {
                "description": "운동 삭제시 호출",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "운동"
                ],
                "summary": "운동 삭제",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {jwt_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "삭제할 id 배열",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공시 200 반환",
                        "schema": {
                            "$ref": "#/definitions/dto.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/save-exercise": {
            "post": {
                "description": "운동 생성시 Id 생략",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "운동"
                ],
                "summary": "운동 생성/수정",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {jwt_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "요청 DTO - 운동 데이터",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ExerciseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공시 200 반환",
                        "schema": {
                            "$ref": "#/definitions/dto.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.BasicResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "err": {
                    "type": "string"
                }
            }
        },
        "dto.ExerciseDateInfo": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string",
                    "example": "YYYY-MM-DD"
                },
                "exercises": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ExerciseDoneInfo"
                    }
                }
            }
        },
        "dto.ExerciseDo": {
            "type": "object",
            "properties": {
                "exercise_id": {
                    "type": "integer"
                },
                "performed_date": {
                    "type": "string",
                    "example": "YYYY-MM-DD"
                }
            }
        },
        "dto.ExerciseDoneInfo": {
            "type": "object",
            "properties": {
                "done": {
                    "type": "boolean"
                },
                "exercise": {
                    "$ref": "#/definitions/dto.ExerciseResponse"
                }
            }
        },
        "dto.ExerciseRequest": {
            "type": "object",
            "properties": {
                "exercise_end_at": {
                    "type": "string",
                    "example": "HH:mm"
                },
                "exercise_start_at": {
                    "type": "string",
                    "example": "HH:mm"
                },
                "id": {
                    "type": "integer"
                },
                "plan_end_at": {
                    "type": "string",
                    "example": "YYYY-MM-DD"
                },
                "plan_start_at": {
                    "type": "string",
                    "example": "YYYY-MM-DD"
                },
                "title": {
                    "type": "string"
                },
                "use_alarm": {
                    "type": "boolean"
                },
                "weekdays": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dto.ExerciseResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "exercise_end_at": {
                    "type": "string",
                    "example": "HH:mm"
                },
                "exercise_start_at": {
                    "type": "string",
                    "example": "HH:mm"
                },
                "id": {
                    "type": "integer"
                },
                "plan_end_at": {
                    "type": "string",
                    "example": "YYYY-MM-DD"
                },
                "plan_start_at": {
                    "type": "string",
                    "example": "YYYY-MM-DD"
                },
                "updated": {
                    "type": "string"
                },
                "use_alarm": {
                    "type": "boolean"
                },
                "weekdays": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dto.ProjectResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                }
            }
        },
        "dto.VideoResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "thumbnail_url": {
                    "type": "string"
                },
                "updated": {
                    "type": "string"
                },
                "video_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
