definitions:
  dto.BasicResponse:
    properties:
      code:
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      err:
        type: string
    type: object
  dto.ExerciseDateInfo:
    properties:
      date:
        example: YYYY-MM-DD
        type: string
      exercises:
        items:
          $ref: '#/definitions/dto.ExerciseDoneInfo'
        type: array
    type: object
  dto.ExerciseDo:
    properties:
      exercise_id:
        type: integer
      performed_date:
        example: YYYY-MM-DD
        type: string
    type: object
  dto.ExerciseDoneInfo:
    properties:
      done:
        type: boolean
      exercise:
        $ref: '#/definitions/dto.ExerciseResponse'
    type: object
  dto.ExerciseRequest:
    properties:
      exercise_end_at:
        example: HH:mm
        type: string
      exercise_start_at:
        example: HH:mm
        type: string
      id:
        type: integer
      plan_end_at:
        example: YYYY-MM-DD
        type: string
      plan_start_at:
        example: YYYY-MM-DD
        type: string
      title:
        type: string
      use_alarm:
        type: boolean
      weekdays:
        items:
          type: integer
        type: array
    type: object
  dto.ExerciseResponse:
    properties:
      created:
        example: 'YYYY-mm-ddTHH:mm:ssZ (ISO8601) '
        type: string
      exercise_end_at:
        example: HH:mm
        type: string
      exercise_start_at:
        example: HH:mm
        type: string
      id:
        type: integer
      plan_end_at:
        example: YYYY-MM-DD
        type: string
      plan_start_at:
        example: YYYY-MM-DD
        type: string
      updated:
        example: 'YYYY-mm-ddTHH:mm:ssZ (ISO8601) '
        type: string
      use_alarm:
        type: boolean
      weekdays:
        items:
          type: integer
        type: array
    type: object
  dto.ProjectResponse:
    properties:
      count:
        type: integer
      name:
        type: string
      project_id:
        type: string
    type: object
  dto.VideoResponse:
    properties:
      created:
        type: string
      duration:
        type: integer
      name:
        type: string
      thumbnail_url:
        type: string
      updated:
        type: string
      video_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /do-exercises:
    post:
      consumes:
      - application/json
      description: 운동 완료/취소시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 운동 완료/취소 데이터
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ExerciseDo'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 운동 기록
      tags:
      - 운동 /exercise
  /get-exercises:
    get:
      description: 운동 조회시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 시작날짜 yyyy-mm-dd
        in: query
        name: start_date
        required: true
        type: string
      - description: 종료날짜 yyyy-mm-dd
        in: query
        name: end_date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 운동정보
          schema:
            items:
              $ref: '#/definitions/dto.ExerciseDateInfo'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 운동 조회
      tags:
      - 운동 /exercise
  /get-projects:
    get:
      description: 운동 동영상 카테고리 조회시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 카테고리 정보
          schema:
            items:
              $ref: '#/definitions/dto.ProjectResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 운동 동영상 카테고리 조회
      tags:
      - 운동 /exercise
  /get-videos:
    get:
      description: 카테고리별 운동 동영상 조회시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: project_id
        in: query
        name: project_id
        required: true
        type: string
      - description: 페이지 default 0
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 동영상 정보
          schema:
            items:
              $ref: '#/definitions/dto.VideoResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 카테고리별 운동 동영상 조회 (20개씩)
      tags:
      - 운동 /exercise
  /remove-exercise:
    post:
      consumes:
      - application/json
      description: 운동 삭제시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 삭제할 id 배열
        in: body
        name: request
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 운동 삭제
      tags:
      - 운동 /exercise
  /save-exercise:
    post:
      description: 운동 생성시 Id 생략
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 요청 DTO - 운동 데이터
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ExerciseRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 운동 생성/수정
      tags:
      - 운동 /exercise
swagger: "2.0"
