definitions:
  dto.BasicResponse:
    properties:
      code:
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      err:
        type: string
    type: object
  dto.FaceScoreRequest:
    properties:
      score:
        type: string
      type:
        type: integer
    type: object
  dto.FaceScoreResponse:
    properties:
      created:
        type: string
      score:
        type: string
      type:
        type: integer
      updated:
        type: string
    type: object
info:
  contact: {}
paths:
  /get-scores:
    get:
      description: 표정 점수 조회시 호출
      parameters:
      - description: 시작날짜 yyyy-mm-dd
        in: query
        name: start_date
        type: string
      - description: 종료날짜 yyyy-mm-dd
        in: query
        name: end_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 표정검사 정보
          schema:
            items:
              $ref: '#/definitions/dto.FaceScoreResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 표정 점수 조회
      tags:
      - 표정
  /save-scores:
    post:
      description: 표정 검사 완료 후 호출
      parameters:
      - description: 요청 DTO - 표정검사 데이터
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/dto.FaceScoreRequest'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 표정 점수 저장
      tags:
      - 표정
swagger: "2.0"
