definitions:
  dto.BasicResponse:
    properties:
      code:
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      err:
        type: string
    type: object
  dto.FaceExamResponse:
    properties:
      title:
        type: string
      type:
        type: integer
      video_id:
        type: string
    type: object
  dto.FaceScoreRequest:
    properties:
      score:
        type: integer
      type:
        type: integer
    type: object
  dto.FaceScoreResponse:
    properties:
      created:
        example: 'YYYY-mm-ddTHH:mm:ss '
        type: string
      score:
        type: integer
      type:
        type: integer
      updated:
        example: 'YYYY-mm-ddTHH:mm:ss '
        type: string
    type: object
  dto.SwaggerExercise:
    properties:
      created:
        type: string
      id:
        type: integer
      title:
        type: string
      type:
        type: integer
      updated:
        type: string
      video_id:
        type: string
    type: object
  dto.SwaggerResponse:
    properties:
      count:
        type: integer
      title:
        type: string
      type:
        type: integer
      videos:
        $ref: '#/definitions/dto.SwaggerExercise'
    type: object
info:
  contact: {}
paths:
  /get-face-exams:
    get:
      description: 표정 검사시 호출
      produces:
      - application/json
      responses:
        "200":
          description: 표정검사지 정보
          schema:
            items:
              $ref: '#/definitions/dto.FaceExamResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 표정검사지 조회
      tags:
      - 표정 /face
  /get-face-exercises:
    get:
      description: 표정 운동 조회시 호출
      produces:
      - application/json
      responses:
        "200":
          description: 표정운동 정보
          schema:
            items:
              $ref: '#/definitions/dto.SwaggerResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 표정운동 조회
      tags:
      - 표정 /face
  /get-face-scores:
    get:
      description: 표정 점수 조회시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 시작날짜 yyyy-mm-dd
        in: query
        name: start_date
        type: string
      - description: 종료날짜 yyyy-mm-dd
        in: query
        name: end_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 표정검사 점수 정보
          schema:
            items:
              $ref: '#/definitions/dto.FaceScoreResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 표정 점수 조회
      tags:
      - 표정 /face
  /save-faces:
    post:
      description: 표정 검사 완료 후 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: '요청 DTO - 표정검사 데이터 ( type: 1: 기쁨 2: 슬픔 3: 놀람 4: 분노 )'
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/dto.FaceScoreRequest'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 표정 점수 저장
      tags:
      - 표정 /face
swagger: "2.0"
