definitions:
  dto.BasicResponse:
    properties:
      code:
        type: string
    type: object
  dto.EmotionRequest:
    properties:
      emotion:
        example: 기분명
        type: string
      id:
        type: integer
      state:
        example: 기분내용
        type: string
    type: object
  dto.EmotionResponse:
    properties:
      created:
        example: 'YYYY-mm-ddTHH:mm:ss '
        type: string
      emotion:
        example: 기분명
        type: string
      id:
        type: integer
      state:
        example: 기분내용
        type: string
      updated:
        example: 'YYYY-mm-ddTHH:mm:ss '
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      err:
        type: string
    type: object
info:
  contact: {}
paths:
  /get-emotions:
    get:
      description: 기분 조회시 호출 (10개씩)
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 시작날짜 yyyy-mm-dd
        in: query
        name: start_date
        type: string
      - description: 종료날짜 yyyy-mm-dd
        in: query
        name: end_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 기분정보
          schema:
            items:
              $ref: '#/definitions/dto.EmotionResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 기분 조회
      tags:
      - 기분 /emotion
  /remove-emotion:
    post:
      consumes:
      - application/json
      description: 기분 삭제시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 삭제할 id 배열
        in: body
        name: request
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 기분 삭제
      tags:
      - 기분 /emotion
  /save-emotion:
    post:
      description: 기분 생성시 Id 생략
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 요청 DTO - 기분 데이터
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.EmotionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 기분 생성/수정
      tags:
      - 기분 /emotion
swagger: "2.0"
