// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: alarm.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlarmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StartAt   string  `protobuf:"bytes,2,opt,name=startAt,proto3" json:"start_at,omitempty"`
	EndAt     string  `protobuf:"bytes,3,opt,name=endAt,proto3" json:"end_at,omitempty"`
	Timestamp string  `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Week      []int32 `protobuf:"varint,5,rep,packed,name=week,proto3" json:"week,omitempty"`
	Type      string  `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Body      string  `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	Uid       int32   `protobuf:"varint,8,opt,name=uid,proto3" json:"uid,omitempty"`
	UseAlarm  bool    `protobuf:"varint,9,opt,name=useAlarm,proto3" json:"useAlarm,omitempty"`
}

func (x *AlarmRequest) Reset() {
	*x = AlarmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alarm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmRequest) ProtoMessage() {}

func (x *AlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alarm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmRequest.ProtoReflect.Descriptor instead.
func (*AlarmRequest) Descriptor() ([]byte, []int) {
	return file_alarm_proto_rawDescGZIP(), []int{0}
}

func (x *AlarmRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AlarmRequest) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *AlarmRequest) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

func (x *AlarmRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *AlarmRequest) GetWeek() []int32 {
	if x != nil {
		return x.Week
	}
	return nil
}

func (x *AlarmRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AlarmRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *AlarmRequest) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AlarmRequest) GetUseAlarm() bool {
	if x != nil {
		return x.UseAlarm
	}
	return false
}

type AlarmResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AlarmResponse) Reset() {
	*x = AlarmResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alarm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlarmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmResponse) ProtoMessage() {}

func (x *AlarmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alarm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmResponse.ProtoReflect.Descriptor instead.
func (*AlarmResponse) Descriptor() ([]byte, []int) {
	return file_alarm_proto_rawDescGZIP(), []int{1}
}

func (x *AlarmResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AlarmRemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Uid int32   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *AlarmRemoveRequest) Reset() {
	*x = AlarmRemoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alarm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlarmRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmRemoveRequest) ProtoMessage() {}

func (x *AlarmRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alarm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmRemoveRequest.ProtoReflect.Descriptor instead.
func (*AlarmRemoveRequest) Descriptor() ([]byte, []int) {
	return file_alarm_proto_rawDescGZIP(), []int{2}
}

func (x *AlarmRemoveRequest) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *AlarmRemoveRequest) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

var File_alarm_proto protoreflect.FileDescriptor

var file_alarm_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61,
	0x6c, 0x61, 0x72, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0xd6, 0x01, 0x0a, 0x0c,
	0x41, 0x6c, 0x61, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x65,
	0x65, 0x6b, 0x18, 0x05, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x77, 0x65, 0x65, 0x6b, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x41,
	0x6c, 0x61, 0x72, 0x6d, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x75, 0x73, 0x65, 0x41,
	0x6c, 0x61, 0x72, 0x6d, 0x22, 0x27, 0x0a, 0x0d, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x38, 0x0a,
	0x12, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x32, 0xa1, 0x01, 0x0a, 0x0c, 0x41, 0x6c, 0x61, 0x72,
	0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x41,
	0x6c, 0x61, 0x72, 0x6d, 0x12, 0x1a, 0x2e, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x41, 0x6c, 0x61, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a,
	0x0b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x12, 0x20, 0x2e, 0x61,
	0x6c, 0x61, 0x72, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x6c, 0x61, 0x72,
	0x6d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x6c,
	0x61, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e,
	0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_alarm_proto_rawDescOnce sync.Once
	file_alarm_proto_rawDescData = file_alarm_proto_rawDesc
)

func file_alarm_proto_rawDescGZIP() []byte {
	file_alarm_proto_rawDescOnce.Do(func() {
		file_alarm_proto_rawDescData = protoimpl.X.CompressGZIP(file_alarm_proto_rawDescData)
	})
	return file_alarm_proto_rawDescData
}

var file_alarm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_alarm_proto_goTypes = []interface{}{
	(*AlarmRequest)(nil),       // 0: alarmservice.AlarmRequest
	(*AlarmResponse)(nil),      // 1: alarmservice.AlarmResponse
	(*AlarmRemoveRequest)(nil), // 2: alarmservice.AlarmRemoveRequest
}
var file_alarm_proto_depIdxs = []int32{
	0, // 0: alarmservice.AlarmService.SetAlarm:input_type -> alarmservice.AlarmRequest
	2, // 1: alarmservice.AlarmService.RemoveAlarm:input_type -> alarmservice.AlarmRemoveRequest
	1, // 2: alarmservice.AlarmService.SetAlarm:output_type -> alarmservice.AlarmResponse
	1, // 3: alarmservice.AlarmService.RemoveAlarm:output_type -> alarmservice.AlarmResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alarm_proto_init() }
func file_alarm_proto_init() {
	if File_alarm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_alarm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlarmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alarm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlarmResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alarm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlarmRemoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alarm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alarm_proto_goTypes,
		DependencyIndexes: file_alarm_proto_depIdxs,
		MessageInfos:      file_alarm_proto_msgTypes,
	}.Build()
	File_alarm_proto = out.File
	file_alarm_proto_rawDesc = nil
	file_alarm_proto_goTypes = nil
	file_alarm_proto_depIdxs = nil
}
