definitions:
  transport.Alarm:
    properties:
      body:
        type: string
      endAt:
        example: yyyy-mm-dd
        type: string
      id:
        type: integer
      startAt:
        example: yyyy-mm-dd
        type: string
      timestamp:
        example: hh:mm
        type: string
      type:
        type: string
      uid:
        description: User ID의 외래키
        type: integer
      week:
        description: '"3,4,5,6" 형식'
        type: string
    type: object
  transport.BasicResponse:
    properties:
      code:
        type: string
    type: object
  transport.ErrorResponse:
    properties:
      err:
        description: wwwwww
        example: account name
        type: string
    type: object
info:
  contact: {}
paths:
  /remove-alarm:
    post:
      consumes:
      - application/json
      description: 알람삭제시 호출
      parameters:
      - description: 요청 DTO - 알람데이터
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/transport.Alarm'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/transport.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/transport.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/transport.ErrorResponse'
      summary: 알람설정
      tags:
      - 알람삭제
  /save-alarm:
    post:
      consumes:
      - application/json
      description: 알람생성시 호출
      parameters:
      - description: 요청 DTO - 알람데이터
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/transport.Alarm'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/transport.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/transport.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/transport.ErrorResponse'
      summary: 알람설정
      tags:
      - 알람생성
swagger: "2.0"
