definitions:
  dto.BasicResponse:
    properties:
      code:
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      err:
        description: wwwwww
        type: string
    type: object
  dto.InquireReplyRequest:
    properties:
      content:
        type: string
      inquire_id:
        type: integer
      reply_type:
        type: boolean
    type: object
  dto.InquireReplyResponse:
    properties:
      content:
        type: string
      created:
        type: string
      id:
        type: integer
      inquire_id:
        type: integer
      reply_type:
        type: boolean
      updated:
        type: string
    type: object
  dto.InquireRequest:
    properties:
      content:
        type: string
      email:
        type: string
      title:
        type: string
    type: object
  dto.InquireResponse:
    properties:
      content:
        type: string
      created:
        type: string
      email:
        type: string
      id:
        type: integer
      replies:
        items:
          $ref: '#/definitions/dto.InquireReplyResponse'
        type: array
      title:
        type: string
      updated:
        type: string
    type: object
info:
  contact: {}
paths:
  /all-inquires:
    get:
      description: 관리자 문의내역 확인시 호출 (10개씩)
      parameters:
      - description: 페이지 번호 default 0
        in: query
        name: page
        type: integer
      - description: 시작날짜 yyyy-mm-dd
        in: query
        name: start_date
        type: string
      - description: 종료날짜 yyyy-mm-dd
        in: query
        name: end_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 문의내역 배열 반환
          schema:
            items:
              $ref: '#/definitions/dto.InquireResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 문의조회(관리자)
      tags:
      - 문의
  /get-inquires:
    get:
      consumes:
      - application/json
      description: 나의문의보기시 호출
      parameters:
      - description: 페이지 번호 default 0
        in: query
        name: page
        type: integer
      - description: 시작날짜 yyyy-mm-dd
        in: query
        name: start_date
        type: string
      - description: 종료날짜 yyyy-mm-dd
        in: query
        name: end_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 문의내역 배열 반환
          schema:
            items:
              $ref: '#/definitions/dto.InquireResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 문의조회(본인)
      tags:
      - 문의
  /inquire-reply:
    post:
      consumes:
      - application/json
      description: 답변/추가문의 등록시 호출
      parameters:
      - description: 요청 DTO - 답변데이터
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.InquireReplyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 답변/추가문의
      tags:
      - 문의
  /remove-inquire/{id}:
    post:
      consumes:
      - application/json
      description: 문의삭제시 호출
      parameters:
      - description: 문의ID
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 문의삭제
      tags:
      - 문의
  /remove-reply/{id}:
    post:
      consumes:
      - application/json
      description: 문의답변/추가문의 삭제시 호출
      parameters:
      - description: 답변/추가문의ID
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 문의답변/추가문의 삭제
      tags:
      - 문의
  /send-inquire:
    post:
      consumes:
      - application/json
      description: 문의등록시 호출
      parameters:
      - description: 요청 DTO - 문의데이터
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.InquireRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 문의하기
      tags:
      - 문의
swagger: "2.0"
