definitions:
  transport.BasicResponse:
    properties:
      code:
        type: string
    type: object
  transport.ErrorResponse:
    properties:
      err:
        description: wwwwww
        type: string
    type: object
  transport.Inquire:
    properties:
      content:
        type: string
      created:
        type: string
      email:
        type: string
      id:
        type: integer
      title:
        type: string
      uid:
        description: user 아이디
        type: integer
      updated:
        type: string
    type: object
  transport.InquireReply:
    properties:
      content:
        type: string
      created:
        type: string
      id:
        type: integer
      inquire_id:
        type: integer
      reply_type:
        type: boolean
      uid:
        type: integer
      updated:
        type: string
    type: object
info:
  contact: {}
paths:
  /get-inquires:
    get:
      description: 관리자 문의내역 확인시 호출
      parameters:
      - description: 페이지 번호 default 0
        in: query
        name: page
        type: integer
      - description: 시작날짜 yyyy-mm-dd
        in: query
        name: start_date
        type: string
      - description: 종료날짜 yyyy-mm-dd
        in: query
        name: end_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 문의내역 배열 반환
          schema:
            items:
              $ref: '#/definitions/transport.Inquire'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/transport.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/transport.ErrorResponse'
      summary: 문의관련
      tags:
      - 문의조회(관리자)
  /inquire-answer:
    post:
      consumes:
      - application/json
      description: 답변등록시 호출
      parameters:
      - description: 요청 DTO - 답변데이터
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/transport.InquireReply'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/transport.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/transport.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/transport.ErrorResponse'
      summary: 문의관련
      tags:
      - 답변하기
  /send-inquire:
    post:
      consumes:
      - application/json
      description: 문의등록시 호출
      parameters:
      - description: 요청 DTO - 문의데이터
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/transport.Inquire'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/transport.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/transport.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/transport.ErrorResponse'
      summary: 문의관련
      tags:
      - 문의하기
swagger: "2.0"
