definitions:
  transport.BasicResponse:
    properties:
      code:
        type: string
    type: object
  transport.ErrorResponse:
    properties:
      err:
        description: wwwwww
        type: string
    type: object
  transport.InquireReply:
    properties:
      content:
        type: string
      date:
        type: string
      id:
        type: integer
      inquireId:
        description: Inquire 아이디
        type: integer
      type:
        description: 답변 또는 추가 문의
        type: boolean
      uid:
        description: user 아이디
        type: integer
    type: object
info:
  contact: {}
paths:
  /inquire-answer:
    post:
      consumes:
      - application/json
      description: 답변등록시 호출
      parameters:
      - description: 요청 DTO - 답변데이터
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/transport.InquireReply'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/transport.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/transport.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/transport.ErrorResponse'
      summary: 알람설정
      tags:
      - 알람생성
swagger: "2.0"
