name: Build and Push Docker Images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed-services: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            admin-video-service: 'admin-video-service/**'
            alarm-service: 'alarm-service/**'
            diet-service: 'diet-service/**'
            email-service: 'email-service/**'
            emotion-service: 'emotion-service/**'
            exercise-service: 'exercise-service/**'
            face-service: 'face-service/**'
            fcm-service: 'fcm-service/**'
            gateway: 'gateway/**'
            inquire-service: 'inquire-service/**'
            medicine-service: 'medicine-service/**'
            sleep-service: 'sleep-service/**'
            user-service: 'user-service/**'
            vocal-service: 'vocal-service/**'

  build-and-push:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.changed-services) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: disterbia94/wellkinson-${{ matrix.service }}:latest

  notify-deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy workflow
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.GH_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy.yml/dispatches \
            -d '{"ref":"main"}'
