definitions:
  dto.BasicResponse:
    properties:
      code:
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      err:
        type: string
    type: object
  dto.LoginRequest:
    properties:
      id_token:
        type: string
      user:
        $ref: '#/definitions/dto.UserRequest'
    type: object
  dto.SuccessResponse:
    properties:
      jwt:
        type: string
    type: object
  dto.UserRequest:
    properties:
      birthday:
        example: YYYY-MM-DD
        type: string
      device_id:
        type: string
      fcm_token:
        type: string
      gender:
        description: 'true:남 false: 여'
        type: boolean
      is_first:
        type: boolean
      name:
        type: string
      phone_num:
        example: "01000000000"
        type: string
      use_auto_login:
        type: boolean
      use_sleep_tracking:
        type: boolean
      user_privacy_protection:
        type: boolean
      user_type:
        type: string
    type: object
  dto.UserResponse:
    properties:
      birthday:
        example: YYYY-MM-DD
        type: string
      created:
        example: 'YYYY-mm-ddTHH:mm:ssZ (ISO8601) '
        type: string
      device_id:
        type: string
      email:
        type: string
      fcm_token:
        type: string
      gender:
        description: 'true:남 false: 여'
        type: boolean
      is_first:
        type: boolean
      name:
        type: string
      phone_num:
        example: "01000000000"
        type: string
      updated:
        example: 'YYYY-mm-ddTHH:mm:ssZ (ISO8601) '
        type: string
      use_auto_login:
        type: boolean
      use_sleep_tracking:
        type: boolean
      user_privacy_protection:
        type: boolean
      user_type:
        type: string
    type: object
info:
  contact: {}
paths:
  /admin-login:
    post:
      consumes:
      - application/json
      description: 관리자 로그인시 호출
      parameters:
      - description: email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 JWT 토큰 반환
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - jwt: []
      summary: 관리자 로그인
      tags:
      - 로그인
  /auto-login:
    post:
      consumes:
      - application/json
      description: 최초 로그인 이후 앱 실행시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 JWT 토큰 반환
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - jwt: []
      summary: 자동로그인
      tags:
      - 로그인
  /get-user:
    post:
      consumes:
      - application/json
      description: 내 정보 조회시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 유저 객체 반환/ ture:남성
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 유저 조회
      tags:
      - 회원조회(본인)
  /google-login:
    post:
      consumes:
      - application/json
      description: 구글로그인 성공시 호출
      parameters:
      - description: 요청 DTO - idToken,기본값 데이터
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 JWT 토큰 반환
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 구글로그인
      tags:
      - 로그인
  /kakao-login:
    post:
      consumes:
      - application/json
      description: 카카오로그인 성공시 호출
      parameters:
      - description: 요청 DTO - dToken,기본값 데이터
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 JWT 토큰 반환
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 카카오로그인
      tags:
      - 로그인
  /set-user:
    post:
      consumes:
      - application/json
      description: 유저 상태영구변경시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 요청 DTO - 업데이트 할 데이터/ ture:남성
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 유저 데이터 변경
      tags:
      - 회원상태 변경(본인)
swagger: "2.0"
