definitions:
  dto.AppVersionResponse:
    properties:
      android_link:
        type: string
      ios_link:
        type: string
      latest_version:
        type: string
    type: object
  dto.AutoLoginRequest:
    properties:
      device_id:
        type: string
      fcm_token:
        type: string
    type: object
  dto.BasicResponse:
    properties:
      code:
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      err:
        type: string
    type: object
  dto.ImageResponse:
    properties:
      thumbnail_url:
        type: string
      url:
        type: string
    type: object
  dto.LinkRequest:
    properties:
      id_token:
        type: string
    type: object
  dto.LinkedResponse:
    properties:
      email:
        type: string
      sns_type:
        type: integer
    type: object
  dto.LoginRequest:
    properties:
      id_token:
        type: string
      user:
        $ref: '#/definitions/dto.UserRequest'
    type: object
  dto.MainServiceResponse:
    properties:
      id:
        type: integer
      title:
        type: string
    type: object
  dto.SuccessResponse:
    properties:
      jwt:
        type: string
    type: object
  dto.UserRequest:
    properties:
      birthday:
        example: YYYY-MM-DD
        type: string
      device_id:
        type: string
      fcm_token:
        type: string
      gender:
        description: 'true:남 false: 여'
        type: boolean
      is_first:
        type: boolean
      name:
        type: string
      phone_num:
        example: "01000000000"
        type: string
      profile_image:
        example: base64 encoding string
        type: string
      use_auto_login:
        type: boolean
      use_services:
        items:
          type: integer
        type: array
      use_sleep_tracking:
        type: boolean
      user_privacy_protection:
        type: boolean
      user_type:
        type: integer
    type: object
  dto.UserResponse:
    properties:
      birthday:
        example: YYYY-MM-DD
        type: string
      created:
        example: 'YYYY-mm-ddTHH:mm:ssZ (ISO8601) '
        type: string
      device_id:
        type: string
      email:
        type: string
      fcm_token:
        type: string
      gender:
        description: 'true:남 false: 여'
        type: boolean
      is_first:
        type: boolean
      linked_emails:
        items:
          $ref: '#/definitions/dto.LinkedResponse'
        type: array
      name:
        type: string
      phone_num:
        example: "01000000000"
        type: string
      profile_image:
        $ref: '#/definitions/dto.ImageResponse'
      sns_type:
        type: integer
      updated:
        example: 'YYYY-mm-ddTHH:mm:ssZ (ISO8601) '
        type: string
      use_auto_login:
        type: boolean
      use_services:
        items:
          $ref: '#/definitions/dto.MainServiceResponse'
        type: array
      use_sleep_tracking:
        type: boolean
      user_privacy_protection:
        type: boolean
      user_type:
        type: integer
    type: object
  dto.VerifyRequest:
    properties:
      code:
        example: 인증번호 6자리
        type: string
      phone_number:
        example: "01000000000"
        type: string
    type: object
info:
  contact: {}
paths:
  /admin-login:
    post:
      consumes:
      - application/json
      description: 관리자 로그인시 호출
      parameters:
      - description: email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 JWT 토큰 반환
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - jwt: []
      summary: 관리자 로그인
      tags:
      - 로그인 /user
  /auto-login:
    post:
      consumes:
      - application/json
      description: 최초 로그인 이후 앱 실행시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 요청 DTO
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.AutoLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 JWT 토큰 반환
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - jwt: []
      summary: 자동로그인
      tags:
      - 로그인 /user
  /get-services:
    get:
      consumes:
      - application/json
      description: 이용하고 싶은 서비스 목록 조회시 호출
      produces:
      - application/json
      responses:
        "200":
          description: 서비스 목록
          schema:
            items:
              $ref: '#/definitions/dto.MainServiceResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 전체 서비스 목록 조회
      tags:
      - 공통 /user
  /get-user:
    post:
      consumes:
      - application/json
      description: 내 정보 조회시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 유저 객체 반환/ ture:남성 user_Type- 0:해당없음 1:파킨슨 환자 2:보호자 sns_type-
            0:카카오 1:구글 2:애플
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 유저 조회
      tags:
      - 회원조회(본인)  /user
  /get-version:
    get:
      consumes:
      - application/json
      description: 최신버전 조회시 호출
      produces:
      - application/json
      responses:
        "200":
          description: 최신 버전 정보
          schema:
            $ref: '#/definitions/dto.AppVersionResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 최신버전 조회
      tags:
      - 공통 /user
  /link-email:
    post:
      consumes:
      - application/json
      description: 계정 연동시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 요청 DTO
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LinkRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 계정 연동
      tags:
      - 계정 연동 /user
  /remvoe-user:
    post:
      consumes:
      - application/json
      description: 회원탈퇴시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 회원탈퇴
      tags:
      - 회원탈퇴 /user
  /send-code/{number}:
    post:
      consumes:
      - application/json
      description: 인증번호 발송시 호출
      parameters:
      - description: 휴대번호
        in: path
        name: number
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 인증번호 발송
      tags:
      - 인증번호 /user
  /set-user:
    post:
      consumes:
      - application/json
      description: 유저 상태영구변경시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 요청 DTO - 업데이트 할 데이터/ ture:남성 user_Type- 0:해당없음 1:파킨슨 환자 2:보호자
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: '요청 처리 실패시 오류 메시지 반환: 오류메시지 "-1" = 번호인증 필요'
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 유저 데이터 변경
      tags:
      - 회원상태 변경(본인)  /user
  /sns-login:
    post:
      consumes:
      - application/json
      description: sns 로그인 성공시 호출
      parameters:
      - description: '요청 DTO - idToken,기본값 데이터 user_type: 0:해당없음 1:파킨슨 환자 2:보호자 /
          최초 로그인 이후 로그인시 fcm_token 만 필요함'
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 JWT 토큰 반환
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: '요청 처리 실패시 오류 메시지 반환: 오류메시지 "-2" = 이미 가입한 번호'
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: sns 로그인
      tags:
      - 로그인 /user
  /verify-code:
    post:
      consumes:
      - application/json
      description: 인증번호 입력 후 호출
      parameters:
      - description: 요청 DTO
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.VerifyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/dto.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 번호 인증
      tags:
      - 인증번호 /user
swagger: "2.0"
